# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#we setup the trigger which set pipeline to run when we push code
#trigger:
# branches:
#     include:
#         - main
trigger:
- none
#To setup VM to use bcos we have many of them
pool:
 vmImage: 'windows-latest'

#we need variables to be reused inside other task
variables:
   buildPlatform : 'Any CPU'
   buildConfiguration : 'Release'
   solution : '**/VOTEAPPMvc.sln'
   project: '**/VOTEAPPMvc.csproj'


#To start buld we need to set Task

steps:
#we set the NugetToolInstaller we remove the input add name
#Add Nuggets 
#Add .NetCore to build 
#Add .Netcore to Bulid
#Add .NetPublish artifact


- task: NuGetToolInstaller@1
  name: 'NuggetToolInstaller'
  displayName: 'Nugget Tool Installer'

- task: NuGetCommand@2
  name: 'NuggetRestore'
  displayName: 'Nugget Restore Packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'Tests'
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration(BuildConfiguration)'

- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts'
  displayName: 'Publish Build Artifacts'
  inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'BillingPipe'
        publishLocation: 'Container'